require("timetorave.plugins-setup")
require("timetorave.core.colorscheme")
require("timetorave.core.keymaps")
require("timetorave.core.options")
require("timetorave.plugins.comment")
require("timetorave.plugins.nvimtree")
require("timetorave.plugins.lualine")
